name: Generate Release Tag
on:
  repository_dispatch:
    types: [create-release-tag]

jobs:
  # testing:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       go-version: ["1.18", "1.19", "1.20"]

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup go
  #       uses: actions/setup-go@v1
  #       with:
  #         go-version: ${{ matrix.go-version}}

  #     - name: Print current golang version
  #       run: echo go version

  #     - name: Install dependencies
  #       run: go get github.com/joho/godotenv

  #     - name: Run Test
  #       run: DEVELOPMENT_API_KEY=${{ secrets.DEVELOPMENT_API_KEY }} go test ./test -v

  # send-test-result:
  #   name: Slack Notification
  #   needs: [testing]
  #   if: always() && (needs.testing.result == 'success' || needs.testing.result == 'failure')
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set Slack Color
  #     id: set_color
  #     run: |
  #       if [ "${{ needs.testing.result }}" == "success" ]; then
  #         echo "color=good" >> $GITHUB_ENV
  #       else
  #         echo "color=danger" >> $GITHUB_ENV
  #       fi

  #   - name: Send Slack Notification
  #     uses: rtCamp/action-slack-notify@v2
  #     env:
  #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #       SLACK_TITLE: "[xendi-go] CI pipeline for ${{ github.event.client_payload.version }}"
  #       SLACK_MESSAGE: 'Test Result: ${{ needs.testing.result }}'
  #       SLACK_COLOR: ${{ steps.set_color.outputs.color }}

  publish-release-tag:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - uses: actions/checkout@v3

      - name: Set the value in bash
        id: parse-changelog
        run: |
          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "${{ github.event.client_payload.changelog }}" | sed -e 's/%0A/\n/g' >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create Release
        id: create-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: ${{ github.event.client_payload.version }}
          body: ${{ steps.parse-changelog.outputs.changelog }}
          draft: false
          prerelease: false
