name: "integration-test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.14", "1.13"]
    name: Test with Go version ${{ matrix.go-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: go test ./...
      - run: go run ./integration_test
        env:
          SECRET_KEY: xnd_development_chBDpzjQZEI8nncBLrWtwau5r7rgiuunCJ4JCqsd68rXemDd74BnRpdO0bIZAMK

  test-premod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.12", "1.11"]
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      working-dir: ./src/github.com/${{ github.repository }}
    name: Test with Go version ${{ matrix.go-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
          ref: ${{ github.event.pull_request.head.ref }} # to solve go get problem with detached HEAD
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: go get -v -u ./...
        working-directory: ${{ env.working-dir }}
      - run: go test ./...
        working-directory: ${{ env.working-dir }}
      - run: go run ./integration_test
        working-directory: ${{ env.working-dir }}
        env:
          SECRET_KEY: xnd_development_chBDpzjQZEI8nncBLrWtwau5r7rgiuunCJ4JCqsd68rXemDd74BnRpdO0bIZAMK
